  name: build-and-test
  on: push
  
  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      
      steps:
        - name: Check out the repo
          uses: actions/checkout@v4

        - name: Git Submodule Update
          run: |
            git pull --recurse-submodules
            git submodule update --remote --recursive

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Build
          run: dotnet build
          
        - name: Test
          run: dotnet test